package easypost

var rateMap = map[string]string{
	"First":                                 "First",
	"Priority":                              "Priority",
	"Express":                               "Express",
	"ParcelSelect":                          "Parcel Select",
	"LibraryMail":                           "Library Mail",
	"MediaMail":                             "Media Mail",
	"CriticalMail":                          "Critical Mail",
	"FirstClassMailInternational":           "First Class Mail International",
	"FirstClassPackageInternationalService": "First Class Package International Service",
	"PriorityMailInternational":             "Priority Mail International",
	"ExpressMailInternational":              "Express Mail International",
	"Ground":                                "Ground",
	"UPSStandards":                          "UPS Standards",
	"UPSSaver":                              "UPS Saver",
	"ExpressPlus":                           "Express Plus",
	"Expedited":                             "Expedited",
	"NextDayAir":                            "Next Day Air",
	"NextDayAirSaver":                       "Next Day Air Saver",
	"NextDayAirEarlyAM":                     "Next Day Air Early AM",
	"2ndDayAir":                             "2nd Day Air",
	"2ndDayAirAM":                           "2nd Day Air AM",
	"3DaySelect":                            "3 Day Select",
	"FEDEX_GROUND":                          "Ground",
	"FEDEX_2_DAY":                           "2 Day",
	"FEDEX_2_DAY_AM":                        "2 Day AM",
	"FEDEX_EXPRESS_SAVER":                   "Express Saver",
	"STANDARD_OVERNIGHT":                    "Standard Overnight",
	"FIRST_OVERNIGHT":                       "First Overnight",
	"PRIORITY_OVERNIGHT":                    "Priority Overnight",
	"INTERNATIONAL_ECONOMY":                 "International Economy",
	"INTERNATIONAL_FIRST":                   "International First",
	"INTERNATIONAL_PRIORITY":                "Internaitonal Priority",
	"GROUND_HOME_DELIVERY":                  "Ground Home Delivery",
	"SMART_POST":                            "Smart Post",
}
